// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wqndqjosytlexhjallpr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndxbmRxam9zeXRsZXhoamFsbHByIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2MjM2MDUsImV4cCI6MjA2NDE5OTYwNX0.CM92dltlrRB5Eppc4dhHpIZxEA4Tp5YWEhBWYwRCTqY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);